/**
 * Generated by Gfx v2.3.2 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.wineshop.client.entities;

import org.granite.client.javafx.JavaFXObject;
import org.granite.messaging.amf.RemoteClass;

@JavaFXObject
@RemoteClass("com.wineshop.entities.Wine")
public class Wine extends WineBase {
}